### ISSUE TITLE
RF01 - Cadastro de Alunos Voluntários(Professores do Projeto)

### ISSUE THREAD

**Issue by jwvIyx** [Eduardogdfrt/Central-oficina2#1]
Cadastro de Aluno Voluntário
Cenário de uso: Um aluno voluntário acessa a página de cadastro, preenche seus dados (nome, email, senha, etc.) e finaliza o cadastro. O sistema deve criar a conta do usuário e exibir uma mensagem de confirmação.

Critérios de aceitação:

O sistema deve validar que todos os campos obrigatórios estão preenchidos.
Se os dados estiverem corretos e completos, o cadastro deve ser bem-sucedido e o usuário deve ver uma mensagem de confirmação.
Caso algum campo esteja incorreto ou incompleto, o sistema deve exibir mensagens de erro apropriadas.

**Comment by fnjunior95** [comment]
Cadastro de Usuários
Cenário de uso: Um usuário acessa a página de cadastro, preenche seus dados (nome, email, senha, etc.) e finaliza o cadastro. O sistema deve criar a conta do usuário e exibir uma mensagem de confirmação.

Critérios de aceitação:

O sistema deve validar que todos os campos obrigatórios estão preenchidos.
Se os dados estiverem corretos e completos, o cadastro deve ser bem-sucedido e o usuário deve ver uma mensagem de confirmação.
Caso algum campo esteja incorreto ou incompleto, o sistema deve exibir mensagens de erro apropriadas.
