### ISSUE TITLE
RF02 - Login de Alunos Voluntários

### ISSUE THREAD

**Issue by jwvIyx** [Eduardogdfrt/Central-oficina2#2]
Login de Usuários
Cenário de uso: Um usuário já cadastrado acessa a página de login, insere seu email e senha, e tenta entrar no sistema.

Critérios de aceitação:

Se as credenciais forem corretas, o usuário deve ser autenticado e redirecionado para o painel principal.
Se as credenciais estiverem incorretas, o sistema deve exibir uma mensagem de erro específica.
Após múltiplas tentativas incorretas, o sistema deve bloquear temporariamente o acesso.

**Comment by fnjunior95** [comment]
Login de Usuários
Cenário de uso: Um usuário já cadastrado acessa a página de login, insere seu email e senha, e tenta entrar no sistema.

Critérios de aceitação:

Se as credenciais forem corretas, o usuário deve ser autenticado e redirecionado para o painel principal.
Se as credenciais estiverem incorretas, o sistema deve exibir uma mensagem de erro específica.
Após múltiplas tentativas incorretas, o sistema deve bloquear temporariamente o acesso.
